### ISSUE TITLE
UX: Payment succeeded page takes a long time

### ISSUE THREAD

**Issue by OmarIthawi** [Zeit-Labs/ecommerce-payfort#7]
```
Payment succeeded. Processing enrollment.. please wait..
For your reference, the payment ID is: ECOMMERCE-169996200016165749
```

Takes too long to load. Is it mandatory to wait that much? Or is it by design.

I recommend adding a load meter and a note `It takes 30 seconds to load, don't close blah blah ...`.

**Comment by shadinaif** [comment]
it was an added delay from my side (hard coded delay) to test the transition screen. It has been removed from the final version
